### ISSUE TITLE
Ideology issues with Gauranlen tree

### ISSUE THREAD

**Issue by Violet-Vibes** [AllenCaine/RimWorld-EnhancementPack#3]
```
Exception in Verse.TickList.Tick: System.NullReferenceException: Object reference not set to an instance of an object
  at RimWorld.CompDryadCocoon.CompTick () [0x00014] in <1b9c4c73530448bcbb33283e1d4d7d05>:0 
  at Verse.ThingWithComps.Tick () [0x00024] in <1b9c4c73530448bcbb33283e1d4d7d05>:0 
  at Verse.TickList.Tick () [0x0017d] in <1b9c4c73530448bcbb33283e1d4d7d05>:0 
     - transpiler net.pardeike.rimworld.lib.harmony: IEnumerable`1 VisualExceptions.RunloopExceptionHandler:Transpiler(IEnumerable`1 instructions)
     - postfix Uuugggg.rimworld.TD_Enhancement_Pack.main: Void TD_Enhancement_Pack.TickGrow_PlantHarvest:Postfix(TickerType ___tickType)
     - postfix Uuugggg.rimworld.TD_Enhancement_Pack.main: Void TD_Enhancement_Pack.TickGrow:Postfix(TickerType ___tickType)
     ```

This happened after my linked pawn to my Gauranlen tree died and my dryads went back to immature/cacoons.

**Comment by AllenCaine** [comment]
I can not replicate this Problem on my RimWorld Version. 
Have you a savefile shortly before this happend?
Occur this problem also when you only used this Mod and Harmony?

**Comment by Violet-Vibes** [comment]
> I can not replicate this Problem on my RimWorld Version.
> Have you a savefile shortly before this happend?
> Occur this problem also when you only used this Mod and Harmony?

Hmm, I'll do some more tests and get back to you

**Comment by Violet-Vibes** [comment]
Seems I'm unable to reproduce this on a new save with the same list so I'll chalk it off as due to installing the mod on a save currently in progress or something.

**Comment by AllenCaine** [comment]
Thanks for the reply
If something else occurs, let me know
