### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by Dicopperline** [AllenCaine/RimWorld-EnhancementPack#4]
Error in mod manager, no buttons in UI ingame. Not working absolutly.  
https://ibb.co/g72hkYz 
https://ibb.co/0ZP64tn
https://ibb.co/Kbf8Jmn
Rimworld 1.3.3087 x64

**Comment by AllenCaine** [comment]
Hey, which Version have you downloaded? 
From your Screenshot it seams, you installed another Version. 
Try this Version and delete the other in your Mods Folder.
https://github.com/AllenCaine/RimWorld-EnhancementPack/releases/tag/2.3

**Comment by Dicopperline** [comment]
it was from steam - https://steamcommunity.com/sharedfiles/filedetails/?id=1339135272
"There's a fork at https://github.com/AllenCaine/RimWorld-EnhancementPack/tree/UpdateToRimWorld1.3 if someone is interested at trying it out. Make issues there as I'm not the author, just relaying."
Wow! https://github.com/AllenCaine/RimWorld-EnhancementPack/releases/tag/2.3 wokr like a charm! Thank you!
(and sorry for my ugly english))

**Comment by AllenCaine** [comment]
Ah i know the problem, you dowloaded the source code directly (By clicking on Code and Download ZIP). In the source code there is no about.xml file and so rimworld throws an error. The about.xml file is first createt when the files are compiled. So always use the files in the releases section of github, on the code section you "should" only find the source code. 
You can gladly post the release link on steam, when someone else have the same probleme.
With this link you get always to the newest Version of this forked Mod. (until Alextd updates its official Mod)
https://github.com/AllenCaine/RimWorld-EnhancementPack/releases 

Nice i can help you, have fun playing
